# This workflow will build the TypeScript code on both the server and client and check for any existing errors.

name: TypeScript Checks

on: push

jobs:
  typescript:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run tsc-checkServer
    - run: npm run tsc-checkClient